### ISSUE TITLE
Allow bigger description and receiver name

### ISSUE THREAD

**Issue by jbojcic1** [ihabunek/hub3-api#4]
Is it possible to allow bigger description and receiver name? For example when I pay salary contributions receiver is "DRŽAVNI PRORAČUN REPUBLIKE HRVATSKE" which is more than 30 chars

**Comment by ihabunek** [comment]
That's a restriction of the HUB3 standard, see Table 1 on page 7 in the spec:
http://www.hub.hr/sites/default/files/2dbc_0.pdf

I find it a bit silly as well, especially since most banks allow longer descriptions, but there it is.
