### ISSUE TITLE
Polja sender.model i sender.reference

### ISSUE THREAD

**Issue by BornaZg** [ihabunek/hub3-api#6]
Dan,

Da li možete dodati polja  sender.model i sender.reference .

Unaprijed zahvaljujem na bilo kakvom odgovoru, a naručito ako dodate tu mogučnost.

Borna ;-)

**Comment by ihabunek** [comment]
Nažalost ta polja nisu predviđena HUB3 standardom pa ih ne mogu dodati. I meni fale npr kod isplate plaća gdje se treba upisati poziv na broj platitelja.

Standard je ovdje, polja su opisana u Tablici 1:
https://www.hub.hr/sites/default/files/inline-files/2dbc_0.pdf

**Comment by BornaZg** [comment]
Bok,

 

Hvala na brzom odgovoru.

Da to mi treba za plaće.

Kako to onda rješavaš ?

Nekim drugim librariem ?

 

 

Borna ;-)

**Comment by ihabunek** [comment]
Ručno upisujem, nemam pametnog rješenja.

**Comment by BornaZg** [comment]
Ne kužim,

kako dobiješ PNG ili JPG s tim podacima ?

Ne možeš ručno, ili ?

**Comment by ihabunek** [comment]
Ne može se te podatke nagurati u bar kod. 

Kad imam uplatnicu koja ima poziv na broj platitelja i skeniram bar kod s nje u mobilnom bankarstvu, onda još ručno moram prepisati poziv na broj platitelja sa uplatnice u bankarstvo. To sam mislio.

**Comment by BornaZg** [comment]
OK, Hvala još jednom.

Ako to nekako riješim na neki drugi način , javim.

 

Borna ;-)
